<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Your PhotoX orders and downloads."><title>PhotoX | Orders and downloads</title><link rel="icon" href="favicon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet"><link href="css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="css/styles.css" rel="stylesheet"><script defer src="site-ad.js"></script></head>
<body class="customer-app page-orders-downloads">
  <nav aria-label="Main navigation" class="navbar navbar-expand-lg py-2"><div class="container-xl"><a aria-label="PhotoX home" class="navbar-brand" href="index.html"><img alt="PhotoX" src="logo.png"></a><button aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler border-0 p-0" data-bs-target="#mainNav" data-bs-toggle="collapse" type="button"><i class="bi bi-list fs-2"></i></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav mx-auto gap-lg-3 mt-3 mt-lg-0"><li class="nav-item"><a class="nav-link" href="index.html">Home</a></li><li class="nav-item"><a class="nav-link" href="events.html">Explore</a></li><li class="nav-item"><a class="nav-link" href="photographers.html">Photographers</a></li><li class="nav-item"><a class="nav-link" href="membership.html">Membership</a></li><li class="nav-item"><a class="nav-link" href="about.html">About</a></li><li class="nav-item"><a class="nav-link" href="index.html#contact">Contact</a></li></ul><div class="d-flex align-items-center gap-3 mt-3 mt-lg-0"><button class="icon-button notification-button" aria-label="Notifications"><i class="bi bi-bell"></i><span>2</span></button><div class="account-menu"><button class="profile-trigger" aria-label="Open account menu"><span class="avatar">LM</span><span class="d-none d-sm-inline">Lebo Mokoena</span><i class="bi bi-chevron-down"></i></button><div class="account-dropdown" role="menu"><div class="account-dropdown-user"><span class="avatar">LM</span><div><strong>Lebo Mokoena</strong><small>lebo.mokoena@example.com</small></div></div><a href="profile-settings.html"><i class="bi bi-person"></i> Profile & settings</a><a href="index.html"><i class="bi bi-box-arrow-left"></i> Log out</a></div></div></div></div></div></nav>
  <main class="workspace-layout container-xl"><aside class="workspace-sidebar" aria-label="Account navigation"><div class="workspace-greeting"><span class="eyebrow-blue">YOUR WORKSPACE</span><h1>Keep the<br><em>good ones.</em></h1></div><nav class="workspace-nav"><a class="workspace-nav-link" href="customer-dashboard.html"><i class="bi bi-grid-1x2"></i><span>Overview</span></a><a class="workspace-nav-link" href="my-photos.html"><i class="bi bi-images"></i><span>My photos</span><b>24</b></a><a class="workspace-nav-link" href="saved-events.html"><i class="bi bi-bookmark"></i><span>Saved events</span></a><a class="workspace-nav-link active" href="orders-downloads.html"><i class="bi bi-bag"></i><span>Orders & downloads</span></a><a class="workspace-nav-link" href="profile-settings.html"><i class="bi bi-person"></i><span>Profile & settings</span></a></nav><div class="workspace-side-note"><i class="bi bi-shield-check"></i><div><strong>Secure delivery</strong><span>Your original files are protected with temporary download links.</span></div></div></aside><section class="workspace-content"><div class="workspace-mobile-heading"><span class="eyebrow-blue">YOUR WORKSPACE</span><h2>Orders.</h2><p>Your purchases, ready when you are.</p></div><section class="workspace-view active"><div class="workspace-view-header"><div><span class="eyebrow-blue">ORDERS & DOWNLOADS</span><h2>Your purchases.</h2><p>Download the files you have bought, whenever you need them.</p></div></div><div class="download-banner"><i class="bi bi-cloud-check"></i><div><strong>12 downloads ready</strong><span>Secure high-resolution files are available for your recent orders.</span></div><a class="btn btn-dark rounded-pill px-4" href="my-photos.html">View photos</a></div><div class="order-table"><div class="order-row order-heading"><span>Order</span><span>Event</span><span>Date</span><span>Total</span><span>Status</span><span></span></div><div class="order-row"><span><strong>PX-000123</strong></span><span>Maties vs Ikeys</span><span>12 Sep 2026</span><span>R200</span><span class="status-pill paid">Paid</span><button aria-label="View order"><i class="bi bi-arrow-up-right"></i></button></div><div class="order-row"><span><strong>PX-000098</strong></span><span>City Marathon 2026</span><span>14 Sep 2026</span><span>R450</span><span class="status-pill paid">Paid</span><button aria-label="View order"><i class="bi bi-arrow-up-right"></i></button></div></div></section></section></main>
  <nav class="workspace-bottom-nav"><a href="customer-dashboard.html"><i class="bi bi-grid-1x2"></i><span>Home</span></a><a href="my-photos.html"><i class="bi bi-images"></i><span>Photos</span></a><a href="saved-events.html"><i class="bi bi-bookmark"></i><span>Saved</span></a><a class="active" href="orders-downloads.html"><i class="bi bi-bag"></i><span>Orders</span></a><a href="profile-settings.html"><i class="bi bi-person"></i><span>Profile</span></a></nav>
  <footer class="footer footer-premium"><div class="container-xl">
   <div class="row g-5 footer-main"><div class="col-lg-5"><a class="footer-logo" href="index.html"><img src="logo.png" alt="PhotoX" style="width:150px"></a><p class="footer-copy">The feeling of being there,<br>kept in a frame.</p><div class="footer-social d-flex gap-3"><a href="#" aria-label="Instagram"><i class="bi bi-instagram"></i></a><a href="#" aria-label="Facebook"><i class="bi bi-facebook"></i></a><a href="#" aria-label="Linkedin"><i class="bi bi-linkedin"></i></a></div></div><div class="col-6 col-lg-2"><p class="footer-label">Explore</p><a href="events.html">Events</a><a href="photographers.html">Photographers</a><a href="blog.html">Journal</a><a href="sponsors.html">Sponsors</a></div><div class="col-6 col-lg-2"><p class="footer-label">For creators</p><a href="photographer-dashboard.html">Creator login</a><a href="upload.html">Upload photos</a><a href="photographers.html">Join PhotoX</a><a href="messages.html">Support</a></div><div class="col-12 col-lg-3"><p class="footer-label">Stay in the frame</p><p class="footer-small">New events, fresh galleries and stories from the field.</p><div class="newsletter"><input aria-label="Email address" placeholder="Your email address" type="email"><button aria-label="Subscribe"><i class="bi bi-arrow-up-right"></i></button></div></div></div><div class="footer-bottom"><span>© 2026 PhotoX</span><span>Privacy · Terms ·</span><span>Made for the moments <i class="bi bi-stars"></i></span></div></div></footer>
  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div aria-live="polite" class="toast" id="photoToast" role="status">
      <div class="toast-body d-flex align-items-center gap-2">
        <i class="bi bi-check-circle-fill"></i><span>Search ready.</span>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js">
  </script> 
  <script src="app.js">
  </script>
</body>
</html>