<!doctype html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Your saved PhotoX events."><title>PhotoX | Saved events</title><link rel="icon" href="favicon.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet"><link href="css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="css/styles.css" rel="stylesheet"><script defer src="site-ad.js"></script></head>
<body class="customer-app events-page page-saved-events">
  <nav aria-label="Main navigation" class="navbar navbar-expand-lg py-2"><div class="container-xl"><a aria-label="PhotoX home" class="navbar-brand" href="/"><img alt="PhotoX" src="logo.png"></a><button aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler border-0 p-0" data-bs-target="#mainNav" data-bs-toggle="collapse" type="button"><i class="bi bi-list fs-2"></i></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav mx-auto gap-lg-3 mt-3 mt-lg-0"><li class="nav-item"><a class="nav-link" href="/">Home</a></li><li class="nav-item"><a class="nav-link" href="/events">Explore</a></li><li class="nav-item"><a class="nav-link" href="/photographers">Photographers</a></li><li class="nav-item"><a class="nav-link" href="/membership">Membership</a></li><li class="nav-item"><a class="nav-link" href="/about">About</a></li><li class="nav-item"><a class="nav-link" href="/#contact">Contact</a></li></ul><div class="d-flex align-items-center gap-3 mt-3 mt-lg-0"><button class="icon-button notification-button" aria-label="Notifications"><i class="bi bi-bell"></i><span>2</span></button><div class="account-menu"><button class="profile-trigger" aria-label="Open account menu"><span class="avatar">LM</span><span class="d-none d-sm-inline">Lebo Mokoena</span><i class="bi bi-chevron-down"></i></button><div class="account-dropdown" role="menu"><div class="account-dropdown-user"><span class="avatar">LM</span><div><strong>Lebo Mokoena</strong><small>lebo.mokoena@example.com</small></div></div><a href="/profile-settings"><i class="bi bi-person"></i> Profile & settings</a><a href="/"><i class="bi bi-box-arrow-left"></i> Log out</a></div></div></div></div></div></nav>
  <main class="workspace-layout container-xl"><aside class="workspace-sidebar" aria-label="Account navigation"><div class="workspace-greeting"><span class="eyebrow-blue">YOUR WORKSPACE</span><h1>Keep the<br><em>good ones.</em></h1></div><nav class="workspace-nav"><a class="workspace-nav-link" href="/customer-dashboard"><i class="bi bi-grid-1x2"></i><span>Overview</span></a><a class="workspace-nav-link" href="/my-photos"><i class="bi bi-images"></i><span>My photos</span><b>24</b></a><a class="workspace-nav-link active" href="/saved-events"><i class="bi bi-bookmark"></i><span>Saved events</span></a><a class="workspace-nav-link" href="/orders-downloads"><i class="bi bi-bag"></i><span>Orders & downloads</span></a><a class="workspace-nav-link" href="/profile-settings"><i class="bi bi-person"></i><span>Profile & settings</span></a></nav><div class="workspace-side-note"><i class="bi bi-shield-check"></i><div><strong>Your privacy matters</strong><span>AI search is only active on galleries where the photographer enables it.</span></div></div></aside><section class="workspace-content"><div class="workspace-mobile-heading"><span class="eyebrow-blue">YOUR WORKSPACE</span><h2>Saved events.</h2><p>Stories worth coming back to.</p></div><section class="workspace-view active"><div class="workspace-view-header"><div><span class="eyebrow-blue">SAVED EVENTS</span><h2>Stories in progress.</h2><p>Keep an eye on events and galleries you care about.</p></div><a class="btn btn-lime rounded-pill px-4" href="/events"><i class="bi bi-compass me-2"></i>Explore events</a></div><div class="account-list"><article><img src="https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=500&q=85" alt="City Marathon"><div><span>RUNNING · 14 SEP 2026</span><h3>City Marathon 2026</h3><p>24,812 photos · Cape Town</p></div><button class="saved-state" aria-label="Remove saved event"><i class="bi bi-bookmark-fill"></i></button></article><article><img src="https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=500&q=85" alt="Rugby match"><div><span>RUGBY · 12 SEP 2026</span><h3>Maties vs Ikeys</h3><p>8,430 photos · Stellenbosch</p></div><button class="saved-state" aria-label="Remove saved event"><i class="bi bi-bookmark-fill"></i></button></article></div></section></section></main>
  <nav class="workspace-bottom-nav"><a href="/customer-dashboard"><i class="bi bi-grid-1x2"></i><span>Home</span></a><a href="/my-photos"><i class="bi bi-images"></i><span>Photos</span></a><a class="active" href="/saved-events"><i class="bi bi-bookmark"></i><span>Saved</span></a><a href="/orders-downloads"><i class="bi bi-bag"></i><span>Orders</span></a><a href="/profile-settings"><i class="bi bi-person"></i><span>Profile</span></a></nav>
  <footer class="footer footer-premium"><div class="container-xl">
   <div class="row g-5 footer-main"><div class="col-lg-5"><a class="footer-logo" href="/"><img src="logo.png" alt="PhotoX" style="width:150px"></a><p class="footer-copy">The feeling of being there,<br>kept in a frame.</p><div class="footer-social d-flex gap-3"><a href="#" aria-label="Instagram"><i class="bi bi-instagram"></i></a><a href="#" aria-label="Facebook"><i class="bi bi-facebook"></i></a><a href="#" aria-label="Linkedin"><i class="bi bi-linkedin"></i></a></div></div><div class="col-6 col-lg-2"><p class="footer-label">Explore</p><a href="/events">Events</a><a href="/photographers">Photographers</a><a href="/blog">Journal</a><a href="/sponsors">Sponsors</a></div><div class="col-6 col-lg-2"><p class="footer-label">For creators</p><a href="/photographer-dashboard">Creator login</a><a href="/upload">Upload photos</a><a href="/photographers">Join PhotoX</a><a href="/messages">Support</a></div><div class="col-12 col-lg-3"><p class="footer-label">Stay in the frame</p><p class="footer-small">New events, fresh galleries and stories from the field.</p><div class="newsletter"><input aria-label="Email address" placeholder="Your email address" type="email"><button aria-label="Subscribe"><i class="bi bi-arrow-up-right"></i></button></div></div></div><div class="footer-bottom"><span>© 2026 PhotoX</span><span>Privacy · Terms ·</span><span>Made for the moments <i class="bi bi-stars"></i></span></div></div></footer>
  <div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div aria-live="polite" class="toast" id="photoToast" role="status">
      <div class="toast-body d-flex align-items-center gap-2">
        <i class="bi bi-check-circle-fill"></i><span>Search ready.</span>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js">
  </script> 
  <script src="app.js">
  </script>
</body>
</html>