# ================================
# photox.aitechnotech.in (Laravel)
# ================================
server {
    listen 80;
    server_name photox.aitechnotech.in;

    root /home/phpteam/public_webpage/php84/photox/public;
    index index.php index.html;

    client_max_body_size 2000M;

    access_log /home/phpteam/public_webpage/php84/photox/error/photox_access.log;
    error_log  /home/phpteam/public_webpage/php84/photox/error/photox_error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PHP_VALUE "error_log=/home/phpteam/public_webpage/php84/photox/error/photox_error.log";
        fastcgi_intercept_errors on;
    }

    location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        access_log off;
    }
}
